### ISSUE TITLE
Perform gap analysis

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/tfa#1]
1. Audit D7 features of TFA
2. Audit this current D8 port started by Cash
3. Create issues in this repo for known gaps

**Comment by nerdstein** [comment]
@irek02 - lets flush out this issue queue

**Comment by nerdstein** [comment]
cc: @varvashenya , @stmixnovich

**Comment by irek02** [comment]
For the spirit of the hackathon we're trying to implement the absolute basic functionality for the module:
1. Specify a TFA method in the general settings.
2. Provide verification method via Google app.
3. Alter the login process to include TFA.

I will post more detailed description of the current state and how far we've gone in our effort.

**Comment by nerdstein** [comment]
Thanks, please submit PRs as you progress. We'll have others review so they can learn from the work you've done

**Comment by irek02** [comment]
Concluding our hackathon 2015 effort. Our goal was to implement the following functionality:
1. Display general TFA settings form
2. Specify the TFA method in the general TFA settings form
3. Setup the TFA method for an individual account
4. Prompt and verify TFA during the login process for the account from above

We achieved the first 3 items for the google app TFA method.

Notes:
1. Pull request to merge all our work for the tfa module: https://github.com/d8-contrib-modules/tfa/pull/3
2. We made an initial port of tfa_basic module to D8 https://github.com/irek02/tfa_basic/tree/8.x-1.x. Adam, feel free to move it to the d8-contrib-modules org.
3. A lot of changes are related to the compliance of coding standards and generally making the modules install/uninstall on D8 without whitescreening a site.

Thanks to Dmitrii and Stas for the most of the work. This is a large update and we can have discussions on the specifics of it in the PR and I'm sure we can provide some assistance on the further porting work!

**Comment by nerdstein** [comment]
Assigning to Doyle to do number 4 in the list

**Comment by doylejd** [comment]
@nerdstein #4 is done. There are still gaps in the functionality provided between D7 and D8. Will leave this open until we get issues created for the outstanding items.

**Comment by therealssj** [comment]
Closing issue, gap analysis is done and accordingly issues have been created.
