### ISSUE TITLE
Update Tfa.php to properly handle Send, Login and Fallback plugins

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/tfa#13]
Currently, the only plugin types that gets loaded properly are TfaValidation and TfaSetup plugins. In the __construct method in the Tfa.php class, use the method that the validation plugin loading uses to load other plugin types. 
- Need to make sure the fallback plugins are being sent in properly.
- Need to update the loading of plugins types to use proper D8 constructs. (See the way it loads Validation plugins for an example.)

_Note:: Will likely need to make updates to tfa_basic to have an example to work with in order to get this working._

**Comment by therealssj** [comment]
TFA.php has been deprecated.
