### ISSUE TITLE
Investigate using parent::build() in TfaUserLoginBlock 

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/tfa#14]
When using the parent::build() function to get the non-form related code from the core UserLoginBlock the submit handler seems to call the UserLoginForm submit handler even after the $build['user_login_form'] is replaced with the TfaLoginForm and returned from the build function.

Figuring out why this happens and resolving the issue (if possible) would allow us to simplify the build() logic and no duplicate what we can use from the UserLoginForm.

**Comment by therealssj** [comment]
This happens because it is as far as I understand it i not possible to call the parent::build() to get the non-form related code as we don't pass any `$form` instance to the function so everything is built from scratch again.
