### ISSUE TITLE
Update TFA to allow configurable Encryption

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/tfa#15]
The current plan is to extend the Encrypt module to allow multiple Encryption configurations (config entities). Once this is done, we should be able to assign an encryption entity to each TfaPlugin type if desired. 

We will need to wait and see how the Encrypt implementation pans out before finalizing this ticket.

**Comment by therealssj** [comment]
https://github.com/d8-contrib-modules/tfa/pull/54
