### ISSUE TITLE
Evaluate fallbacks on top of the primary TFA settings

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/tfa#16]
1. Look at behaviors of how this works
2. Leverage existing plugins

**Comment by nerdstein** [comment]
User-specific selection as fallback: https://www.drupal.org/node/2478307

**Comment by therealssj** [comment]
Yes.
The admin form currently does not have any option for fallback plugins.
I agree with the D7 approach of having a default plugin and a list of fallback plugins.

Having this implemented will answer alot of TODO remarks left in the plugin

**Comment by nerdstein** [comment]
I am cool with that.

**Comment by therealssj** [comment]
This works in latest branch.
