### ISSUE TITLE
Implement role check option for tfa setup

### ISSUE THREAD

**Issue by therealssj** [d8-contrib-modules/tfa#19]
Add option to check which roles should have tfa setup.
TFA should only be required by these roles.

**Comment by nerdstein** [comment]
Cool!

**Comment by dbjpanda** [comment]
TFA setup should be allowed to all authenticated users. i.e  any authenticated user can set up his own TFA in his side. Its really difficult to setup TFA for all site users on behalf of them by the admin. And it is possible by simply adding  _*__user_is_logged_in: 'TRUE' *__ option to  setup form route. So no need to be worried.

**Comment by therealssj** [comment]
Use case:
I enabled TFA but I only want users with admin rights to be required to set it, normal authenticated users should not require TFA.
Currently there is no demarcation between user roles for TFA.

**Comment by dbjpanda** [comment]
There should be a "force user option" in root admin side which will force any user you want to enable TFA for him/her. For this we need to use conditional Symfony in *.services.yml to enable or disable the service for particular user( May be admin or user). @attiks @nerdstein  M i right ?

**Comment by nerdstein** [comment]
The role selection is probably good (because it's tied to the permission system). The force option is also good, but I think is separate from the role-based selection.

@dbjpanda can you add a new issue for forced usage of TFA?

**Comment by therealssj** [comment]
In this pull request https://github.com/d8-contrib-modules/tfa/pull/17 
It says that forcing the user to use TFA results in errors so will also need to check why that is happening

**Comment by therealssj** [comment]
Okay i just realized that this can controlled by the admin through the permissions page.
Now should we be adding this on the TFA configuration page?
If we do we will also have to add an option for the permissions of various plugins also as it will not make any sense if the admin can control permissions of TFA on that page only but for permissions of various plugins he has to go to  the permissions page.

@nerdstein what are your thoughts??

**Comment by therealssj** [comment]
This can be controlled by the permissions page. Closing it.
