### ISSUE TITLE
Better to replace hook_user_login

### ISSUE THREAD

**Issue by dbjpanda** [d8-contrib-modules/tfa#20]
I was just looking some codes in tfa.module file and I think it is better to replace "hook_user_login" with "changing route from Old UserLoginForm to NewUserLogin by registering an event subscriber service". We should try to use Symfony rich and Object Oriented Programming (_.class) rather than procedural PHP code. (_.module).

**Comment by nerdstein** [comment]
Agreed, maybe an EventSubscriber

**Comment by dbjpanda** [comment]
Thanks. I have already implemented this in Ga_Login. It will help in better service injection and Unit test.

**Comment by nerdstein** [comment]
Let's get rid of hook_user_login altogether
