### ISSUE TITLE
Update the configuration page

### ISSUE THREAD

**Issue by therealssj** [d8-contrib-modules/tfa#21]
Issues:
1) No mention of fallback plugins? How are we going to decide fallback plugins?
2) After the configuration is saved, there is no mention of what the user should do next.
    Having a hyperlink to the set up page( when required ) would be a much better!

Any more views are welcome!

**Comment by nerdstein** [comment]
Fallback: I am not sure I have a preference on what the fallback plugins are, as long as they are generic and widely applicable. They could ship with TFA and be set in the install file.

The config message would be great

**Comment by therealssj** [comment]
Currently the setting is like we have multiple validation plugins which is kind of vague.
What i was thinking was, in the Validation plugins table we add a labels on various selected plugins based on their weight.
Like the first one be default and rest selected be labelled as fallback plugins.

**Comment by nerdstein** [comment]
Validation plugins do not really have a table, they use annotations and are pulled from the plugin api. I think you can achieve this by having the install set the default plugin and let the selection pull all available from the plugin system if overridden

**Comment by therealssj** [comment]
I meant display that in the admin configuration pages. We wouldnt store it anywhere but use the same approach in the module to decide which would be the default and others as fallback.

**Comment by nerdstein** [comment]
Cool ok

**Comment by therealssj** [comment]
If you have any other approach you would like for this please do share!

**Comment by therealssj** [comment]
Should we be showing the various plugins if tfa has not been enabled?
In D7 we show the plugins only after 'Enable TFA' is checked?

**Comment by therealssj** [comment]
At this point the configuration form has been updated quite a bit.
Things that need to be done.
- Let the plugins build and validate the configuration form.
- Display active and available validation plugins.

**Comment by therealssj** [comment]
https://github.com/d8-contrib-modules/tfa/pull/54 Added all existing configuration options.
