### ISSUE TITLE
Allow login without validation if not setup yet

### ISSUE THREAD

**Issue by therealssj** [d8-contrib-modules/tfa#24]
The user should be allowed to login 2-3 times without validation if he/she has not set up the required validation yet.

**Comment by nerdstein** [comment]
This should be an administrative configuration (which I believe we noted)

**Comment by therealssj** [comment]
I had a doubt, should i just show this to user as a warning on the front page or redirect him to a page with the warning and a proceed button to front page?

First approach seems more better for UX  but I wonder if it will have the same affect as redirecting to a new page where the user will definitely notice something is really off.

**Comment by nerdstein** [comment]
So, the admin configuration should set this. Basically "Enforce after login attempts" configuration that has thw following options: Never, 1, 2, 3, ...., 100

Ideally we show the user a message that they will be forced to use TFA after "Y" more attempts.

Once forced, the user is redirected automatically

**Comment by therealssj** [comment]
cool! :)
On this now! :)

**Comment by therealssj** [comment]
Done in https://github.com/d8-contrib-modules/tfa/pull/45
